#define GLINTS_ENABLED true
#define TRANSLUCENCY_ENABLED true
#define PLAYER_ENABLED true
#define SKYBOXES_ENABLED true
#define TEXTURE_PROPERTIES_ENABLED true
#define COLOR_RESTORATIONS_ENABLED true

#define ANCHORS_ENABLED true
#define EFFECTS_ENABLED true
#define MOVEMENTS_ENABLED true
#define TILES_ENABLED true
#define TRANSITIONS_ENABLED true

#define HIDE_SCOREBOARD_NUMBERS_ENABLED true
#define DISABLE_TEXT_SHADOWS_ENABLED true
#define VERTICAL_SLIDE_ENABLED true

#define DISABLE_BADGES_ENABLED true